### ISSUE TITLE
Lots of established connections with no cleanup

### ISSUE THREAD

**Issue by AnubisSec** [MythicAgents/poseidon#30]
I've noticed while using poseidon, that there are a LOT of established conns that get generated and never cleaned up, and get progressively worse the lower you make the sleep, see an example below: 

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/38790814/210826287-914450e2-1a1f-4460-adb6-38d41242042a.png">

**Comment by its-a-feature** [comment]
I was actually working on that a few weeks ago and forgot to push the changes, https://github.com/MythicAgents/poseidon/commit/55af60ae6065de771fa3e0ea93e67002147c8dd6 (latest push) should now address that. Essentially, there was an http client created within a for loop which would stay around way longer than expected due to some async goroutines in the background within the http library. I refactored and pulled the creation outside of the loop, so it should be a lot better now

**Comment by AnubisSec** [comment]
Oh that's awesome! Thank you so much! I'll test it out tomorrow!

**Comment by AnubisSec** [comment]
Yup is working great! Thank you so much, i'll close this out
